# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        id: node-setup
        with:
          node-version: '16.x'
      - name: Install dependencies
        id: install-deps
        run: yarn install --frozen-lockfile
      - name: Lint
        id: lint-app
        run: yarn lint
      - name: Build
        id: build-app
        run: yarn build
