# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v3
        id: node-setup
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: Install dependencies
        id: install-deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        id: lint-app
        run: pnpm lint
      - name: Build
        id: build-app
        run: pnpm build
